"""Indexing orchestration with incremental staleness.

Pipeline per file: discover -> (staleness check) -> parse -> chunk -> embed ->
upsert into the store. Staleness is two-tier:

* **Fast path (mtime):** a previously-indexed file whose mtime is unchanged is
  skipped entirely.
* **Content path (hash):** a file whose mtime changed is re-hashed; if the hash
  matches the stored one (a false alarm like ``touch``), it's skipped; only a
  real content change re-chunks/re-embeds that file.

New files are added; deleted files are removed. ``--force`` drops everything and
rebuilds. The embed-model/dimension mismatch is detected up front and forces a
full rebuild so we never serve vectors computed by a different embedding model.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn

from code_explain.chunker import file_sha256
from code_explain.config import Config
from code_explain.discovery import discover_files
from code_explain.embedder import Embedder
from code_explain.parser import parse_file
from code_explain.store import SQLiteVecStore, FileRecord

log = logging.getLogger(__name__)


@dataclass
class IndexReport:
    n_files: int = 0
    n_indexed: int = 0
    n_skipped: int = 0
    n_chunks: int = 0
    n_errors: int = 0
    duration: float = 0.0

    @property
    def ok(self) -> bool:
        return self.n_errors == 0


def ensure_index_dir(cfg: Config) -> None:
    cfg.index_dir.mkdir(parents=True, exist_ok=True)
    _write_index_ignore(cfg)


def _write_index_dir_gitignore(cfg: Config) -> None:
    """Make the in-repo index dir self-ignoring without touching the user's
    top-level .gitignore."""
    gi = cfg.index_dir / ".gitignore"
    if not gi.exists():
        gi.write_text("# Generated by code-explain. Safe to delete; it will be recreated.\n*\n")
    readme = cfg.index_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            "# code-explain index\n\n"
            "Generated by `code-explain`. Contains the vector index and config for\n"
            "this repo. Safe to delete at any time (run `code-explain index` to rebuild).\n"
        )


def _write_index_ignore(cfg: Config) -> None:
    # Only write the ignore helper if the index lives inside the repo.
    try:
        cfg.db_path.resolve().relative_to(cfg.repo_path.resolve())
    except ValueError:
        return  # index is outside the repo; nothing to ignore
    _write_index_dir_gitignore(cfg)


def open_store(cfg: Config, *, force: bool = False) -> SQLiteVecStore:
    """Open the store, forcing a rebuild if the embedding model/dim changed.

    Factory: returns a :class:`LanceDBStore` when ``cfg.vector_backend ==
    "lancedb"`` (requires the ``lancedb`` extra), else the default
    :class:`SQLiteVecStore`. Both implement the same surface; graph + hybrid
    FTS features are SQLite-only and degrade to vector-only under LanceDB.
    """
    if cfg.vector_backend == "lancedb":
        from code_explain.lancedb_store import LanceDBStore

        store = LanceDBStore(cfg)  # type: ignore[assignment]
    else:
        store = SQLiteVecStore(cfg.db_path, embed_dim=cfg.embed_dim)
    store.open()
    stored_model = store.stored_embed_model()
    stored_dim = store.stored_embed_dim()

    model_changed = stored_model is not None and stored_model != cfg.embed_model
    dim_changed = stored_dim is not None and stored_dim != cfg.embed_dim
    if (model_changed or dim_changed) and not force:
        log.warning(
            "Embedding model/dim changed (stored=%s/%s, configured=%s/%s); "
            "forcing a full rebuild.",
            stored_model, stored_dim, cfg.embed_model, cfg.embed_dim,
        )
        _drop_all(store)
    if force:
        _drop_all(store)

    store.set_meta("embed_model", cfg.embed_model)
    store.set_meta("embed_dim", str(cfg.embed_dim))
    store.set_meta("embed_n_ctx", str(cfg.embed_n_ctx))
    return store


def _drop_all(store: SQLiteVecStore) -> None:
    """Drop all stored data via the store's own ``drop_all`` (backend-agnostic)."""
    store.drop_all()


def index_repo(
    cfg: Config,
    *,
    force: bool = False,
    console: Console | None = None,
    embedder: Embedder | None = None,
) -> tuple[IndexReport, SQLiteVecStore]:
    """Index (or incrementally re-index) the repo. Returns (report, store)."""
    console = console or Console(quiet=True)
    report = IndexReport()
    start = time.time()

    ensure_index_dir(cfg)
    store = open_store(cfg, force=force)
    embedder = embedder or Embedder(cfg)

    files = discover_files(cfg.repo_path)
    report.n_files = len(files)
    existing = store.get_file_records() if not force else {}

    # Determine the work set.
    to_index: list[Path] = []
    to_delete: list[str] = []
    seen_rels: set[str] = set()
    for f in files:
        rel = f.relative_to(cfg.repo_path).as_posix()
        seen_rels.add(rel)
        rec = existing.get(rel)
        try:
            stat = f.stat()
        except OSError:
            continue
        if rec is not None and abs(rec.mtime - stat.st_mtime) < 1e-6:
            # Fast path: unchanged.
            report.n_skipped += 1
            continue
        to_index.append(f)
    if not force:
        for rel in existing:
            if rel not in seen_rels:
                to_delete.append(rel)

    # Delete removed files.
    for rel in to_delete:
        store.delete_file(rel)

    if not to_index:
        report.duration = time.time() - start
        return report, store

    # Parse + embed + upsert, with a progress bar.
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        console=console,
        transient=True,
    ) as progress:
        task = progress.add_task("Indexing", total=len(to_index))
        for path in to_index:
            try:
                indexed = _index_one(cfg, store, embedder, path)
                if indexed:
                    report.n_indexed += 1
                else:
                    report.n_skipped += 1
            except Exception as exc:
                report.n_errors += 1
                log.warning("failed to index %s: %s", path, exc)
            progress.advance(task)
            # refresh chunk count lazily to avoid per-file queries

    report.n_chunks = store.count_chunks()
    store.set_meta("last_index_at", str(time.time()))
    report.duration = time.time() - start
    return report, store


def _index_one(cfg: Config, store: SQLiteVecStore, embedder: Embedder, path: Path) -> bool:
    """Index one file. Returns True if it was re-chunked/re-embedded, False if
    skipped (content unchanged despite an mtime bump)."""
    rel = path.relative_to(cfg.repo_path).as_posix()
    source = path.read_bytes()
    file_hash = file_sha256(source)
    stat = path.stat()
    mtime = float(stat.st_mtime)
    indexed_at = time.time()

    # Content path: if mtime changed but hash matches a stored record, skip.
    rec = store.get_file_records().get(rel)
    if rec is not None and rec.file_hash == file_hash:
        # mtime changed but content is identical (e.g. a touch): update the
        # files row mtime only, leaving chunks/embeddings intact.
        store.touch_file(rel, mtime, indexed_at)
        return False

    chunks = parse_file(path, source, file_hash, mtime, rel)
    if not chunks:
        return False
    embeddings = embedder.embed_batch([c.text for c in chunks])
    store.upsert_file(
        FileRecord(
            rel_path=rel,
            lang=chunks[0].lang,
            file_hash=file_hash,
            mtime=mtime,
            n_chunks=len(chunks),
            indexed_at=indexed_at,
        ),
        chunks,
        embeddings,
    )
    return True


def is_stale(cfg: Config, store: SQLiteVecStore | None = None) -> bool:
    """True if the index is missing or any tracked file changed/new/removed."""
    own_store = store is None
    store = store or SQLiteVecStore(cfg.db_path, embed_dim=cfg.embed_dim)
    try:
        if own_store:
            store.open()
        if store.count_files() == 0:
            return True
        existing = store.get_file_records()
        current_rels: set[str] = set()
        for f in discover_files(cfg.repo_path):
            rel = f.relative_to(cfg.repo_path).as_posix()
            current_rels.add(rel)
            rec = existing.get(rel)
            try:
                mtime = f.stat().st_mtime
            except OSError:
                continue
            if rec is None or abs(rec.mtime - mtime) >= 1e-6:
                return True
        return bool(set(existing) - current_rels)
    finally:
        if own_store:
            store.close()